---
# ==============================================================================
# Master Application Deployment Playbook
# ==============================================================================

- name: Deploy BankPro Microservice Application
  hosts: app_servers
  become: yes
  gather_facts: yes

  roles:
    - app-deploy
