---
# ==============================================================================
# Nginx Role Service Handlers
# ==============================================================================

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
